name: build docker
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - store/dockerfiles/**
jobs:
  push:
    name: "dockerimages:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - trackmania2020
          - evosc

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./store/dockerfiles/${{ matrix.game }}
          file: ./store/dockerfiles/${{ matrix.game }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/moonub/dockerfiles:${{ matrix.game }}
